
package forms;


import java.awt.event.KeyEvent;
import pfp3.ColaPaquetes;
import pfp3.Paquete;


/**
 *
 * @author ProcesosE
 */
public class JPaquete extends javax.swing.JFrame {
//Paquete cp;
    ColaPaquetes cp;
    /**
     * Creates new form FRegistro
     */
    public JPaquete() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numeroSeguimientoTextField = new javax.swing.JTextField();
        remitenteTextField = new javax.swing.JTextField();
        destinatarioTextField = new javax.swing.JTextField();
        departamentoRecepcionTextField = new javax.swing.JTextField();
        departamentoDestinoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        descripcionPaqueteTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pesoTextField = new javax.swing.JTextField();
        estadoComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        clasificacionComboBox = new javax.swing.JComboBox<>();
        ButtonRegistar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registros de envios MONARCA");
        setResizable(false);

        jLabel1.setText("No. Seguimiento:");

        jLabel2.setText("Remitente:");

        jLabel3.setText("Destinatario:");

        jLabel4.setText("Dep. Recepcion:");

        jLabel5.setText("Dep. Destinatario:");

        numeroSeguimientoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroSeguimientoTextFieldActionPerformed(evt);
            }
        });
        numeroSeguimientoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroSeguimientoTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroSeguimientoTextFieldKeyTyped(evt);
            }
        });

        remitenteTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                remitenteTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                remitenteTextFieldKeyTyped(evt);
            }
        });

        destinatarioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                destinatarioTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                destinatarioTextFieldKeyTyped(evt);
            }
        });

        departamentoRecepcionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                departamentoRecepcionTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                departamentoRecepcionTextFieldKeyTyped(evt);
            }
        });

        departamentoDestinoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                departamentoDestinoTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                departamentoDestinoTextFieldKeyTyped(evt);
            }
        });

        jLabel6.setText("Descripcion:");

        descripcionPaqueteTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descripcionPaqueteTextFieldKeyPressed(evt);
            }
        });

        jLabel7.setText("Peso de Paquete:");

        pesoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesoTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesoTextFieldKeyTyped(evt);
            }
        });

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recibido", "En Transito", "Entregado", " " }));
        estadoComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                estadoComboBoxKeyPressed(evt);
            }
        });

        jLabel8.setText("Estado:");

        jLabel9.setText("Clasificacion:");

        clasificacionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sobre", "Bolsa", "Paquete Mediano", "Paquete Grande" }));
        clasificacionComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clasificacionComboBoxKeyPressed(evt);
            }
        });

        ButtonRegistar.setText("Registrar");
        ButtonRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistarActionPerformed(evt);
            }
        });

        jLabel10.setText("Unidad en libras.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(departamentoDestinoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numeroSeguimientoTextField)
                                    .addComponent(remitenteTextField)
                                    .addComponent(destinatarioTextField)
                                    .addComponent(departamentoRecepcionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descripcionPaqueteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(45, 45, 45))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pesoTextField)
                                        .addComponent(estadoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clasificacionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(ButtonRegistar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(numeroSeguimientoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(remitenteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(descripcionPaqueteTextField))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(destinatarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(departamentoRecepcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(departamentoDestinoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(clasificacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(ButtonRegistar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistarActionPerformed
        // TODO add your handling code here:
        Paquete pack = new Paquete();
        
    
        String numeroSeguimiento = numeroSeguimientoTextField.getText();
        String remitente = remitenteTextField.getText();
        String destinatario = destinatarioTextField.getText();
       
        String departamentoRecepcion = departamentoRecepcionTextField.getText();
        String departamentoDestino = departamentoDestinoTextField.getText();
        String descripcionPaquete = descripcionPaqueteTextField.getText();
        double peso = Double.parseDouble(pesoTextField.getText());
        String estado =  estadoComboBox.getSelectedItem().toString();
        String clasificacion =  clasificacionComboBox.getSelectedItem().toString();
        
        pack.setNumeroSeguimiento(numeroSeguimiento);
        pack.setRemitente(remitente);
        pack.setDestinatario(destinatario);
        pack.setDepartamentoRecepcion(departamentoRecepcion);
        pack.setDepartamentoDestino(departamentoDestino);
        pack.setDescripcionPaquete(descripcionPaquete);
        pack.setPeso(peso);
        pack.setEstado(estado);
        pack.setClasificacion(clasificacion);
        

         ColaPaquetes colaPaquetes = new ColaPaquetes(pack);

    }//GEN-LAST:event_ButtonRegistarActionPerformed

    private void numeroSeguimientoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroSeguimientoTextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            remitenteTextField.requestFocus();
        }    
    }//GEN-LAST:event_numeroSeguimientoTextFieldKeyPressed

    private void remitenteTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remitenteTextFieldKeyPressed
       //traslada en puntero de un lugar hacia otro
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            destinatarioTextField.requestFocus(); 
        } 
    }//GEN-LAST:event_remitenteTextFieldKeyPressed

    private void destinatarioTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_destinatarioTextFieldKeyPressed
        //traslada en puntero de un lugar hacia otro
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            departamentoRecepcionTextField.requestFocus();
        } 
    }//GEN-LAST:event_destinatarioTextFieldKeyPressed

    private void departamentoRecepcionTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departamentoRecepcionTextFieldKeyPressed
        //traslada en puntero de un lugar hacia otro
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            departamentoDestinoTextField.requestFocus();
        }  
    }//GEN-LAST:event_departamentoRecepcionTextFieldKeyPressed

    private void departamentoDestinoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departamentoDestinoTextFieldKeyPressed
        //traslada en puntero de un lugar hacia otro
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            descripcionPaqueteTextField.requestFocus();
        }  
    }//GEN-LAST:event_departamentoDestinoTextFieldKeyPressed

    private void descripcionPaqueteTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionPaqueteTextFieldKeyPressed
       //traslada en puntero de un lugar hacia otro       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            pesoTextField.requestFocus();
        }  
    }//GEN-LAST:event_descripcionPaqueteTextFieldKeyPressed

    private void pesoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesoTextFieldKeyPressed
        //traslada en puntero de un lugar hacia otro
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            estadoComboBox.requestFocus();
        }  
    }//GEN-LAST:event_pesoTextFieldKeyPressed

    private void estadoComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estadoComboBoxKeyPressed
        //traslada en puntero de un lugar hacia otro
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             clasificacionComboBox.requestFocus();
        }  
    }//GEN-LAST:event_estadoComboBoxKeyPressed

    private void clasificacionComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clasificacionComboBoxKeyPressed
        //traslada en puntero de un lugar hacia otro
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             ButtonRegistar.requestFocus();
        } 
    }//GEN-LAST:event_clasificacionComboBoxKeyPressed

    private void numeroSeguimientoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroSeguimientoTextFieldKeyTyped
        // VALIDAR SOLO NUMEROS
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar) || validar == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_numeroSeguimientoTextFieldKeyTyped

    private void remitenteTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remitenteTextFieldKeyTyped
        // VALIDAR SOLO LETRAS
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_remitenteTextFieldKeyTyped

    private void destinatarioTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_destinatarioTextFieldKeyTyped
        // VALIDAR SOLO LETRAS
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_destinatarioTextFieldKeyTyped

    private void departamentoRecepcionTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departamentoRecepcionTextFieldKeyTyped
        // VALIDAR SOLO LETRAS
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_departamentoRecepcionTextFieldKeyTyped

    private void departamentoDestinoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departamentoDestinoTextFieldKeyTyped
        // VALIDAR SOLO LETRAS
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_departamentoDestinoTextFieldKeyTyped

    private void pesoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesoTextFieldKeyTyped
        // VALIDAR SOLO NUMEROS
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar) || validar == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        } 
    }//GEN-LAST:event_pesoTextFieldKeyTyped

    private void numeroSeguimientoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroSeguimientoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroSeguimientoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("FlatLaf Light".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new JPaquete().setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegistar;
    private javax.swing.JComboBox<String> clasificacionComboBox;
    private javax.swing.JTextField departamentoDestinoTextField;
    private javax.swing.JTextField departamentoRecepcionTextField;
    private javax.swing.JTextField descripcionPaqueteTextField;
    private javax.swing.JTextField destinatarioTextField;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numeroSeguimientoTextField;
    private javax.swing.JTextField pesoTextField;
    private javax.swing.JTextField remitenteTextField;
    // End of variables declaration//GEN-END:variables
}
